### ISSUE TITLE
Add to options arguments to be passed to the sqlite process

### ISSUE THREAD

**Issue by yoavain** [WebReflection/sqlite-tag-spawned#2]
For example: separator can be very useful.
I'm trying to use query instead of get (due to #1) and my data contains the default separator "|"

**Comment by WebReflection** [comment]
as mentioned there:

  * if you need to `get` data you need to use `get` or `all`
  * separator makes no sense in here because the output is `-json` ... if you don't have the right output is because you are not using SQLite 3.33 or higher

**Comment by WebReflection** [comment]
@yoavain as the #1 bug has been fixed, do you need anything else? I am a bit skeptical at exposing all arguments because I don't have time to fix issues peole might cause by abusing those arguments ... as it is now, everything one needs is there and works out of the box. `-bail` and `-json` looks like the only arguments we should care about in this project, thoughts?

**Comment by yoavain** [comment]
Yes, I just saw #1 is fixed, so you're right. 
The json API is everything I need.
I guess adding options means more maintenance, and more error prone...
